<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'LosDomain\Module'                => __DIR__ . '/src/LosDomain/Module.php',
    'LosDomain\Options\DomainOptions' => __DIR__ . '/src/LosDomain/Options/DomainOptions.php',
    'LosDomain\Options\ModuleOptions' => __DIR__ . '/src/LosDomain/Options/ModuleOptions.php',
    'LosDomain\Service\Domain'        => __DIR__ . '/src/LosDomain/Service/Domain.php',
);
